/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.tsx",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // Primary brand color
        primary: {
          0: "rgb(var(--color-primary-0) / <alpha-value>)",
          50: "rgb(var(--color-primary-50) / <alpha-value>)",
          100: "rgb(var(--color-primary-100) / <alpha-value>)",
          200: "rgb(var(--color-primary-200) / <alpha-value>)",
          300: "rgb(var(--color-primary-300) / <alpha-value>)",
          400: "rgb(var(--color-primary-400) / <alpha-value>)",
          500: "rgb(var(--color-primary-500) / <alpha-value>)",
          600: "rgb(var(--color-primary-600) / <alpha-value>)",
          700: "rgb(var(--color-primary-700) / <alpha-value>)",
          800: "rgb(var(--color-primary-800) / <alpha-value>)",
          900: "rgb(var(--color-primary-900) / <alpha-value>)",
          950: "rgb(var(--color-primary-950) / <alpha-value>)",
        },
        // Secondary - for subtle elements
        secondary: {
          0: "rgb(var(--color-secondary-0) / <alpha-value>)",
          50: "rgb(var(--color-secondary-50) / <alpha-value>)",
          100: "rgb(var(--color-secondary-100) / <alpha-value>)",
          200: "rgb(var(--color-secondary-200) / <alpha-value>)",
          300: "rgb(var(--color-secondary-300) / <alpha-value>)",
          400: "rgb(var(--color-secondary-400) / <alpha-value>)",
          500: "rgb(var(--color-secondary-500) / <alpha-value>)",
          600: "rgb(var(--color-secondary-600) / <alpha-value>)",
          700: "rgb(var(--color-secondary-700) / <alpha-value>)",
          800: "rgb(var(--color-secondary-800) / <alpha-value>)",
          900: "rgb(var(--color-secondary-900) / <alpha-value>)",
          950: "rgb(var(--color-secondary-950) / <alpha-value>)",
        },
        // Error/Danger states
        error: {
          0: "rgb(var(--color-error-0) / <alpha-value>)",
          50: "rgb(var(--color-error-50) / <alpha-value>)",
          100: "rgb(var(--color-error-100) / <alpha-value>)",
          200: "rgb(var(--color-error-200) / <alpha-value>)",
          300: "rgb(var(--color-error-300) / <alpha-value>)",
          400: "rgb(var(--color-error-400) / <alpha-value>)",
          500: "rgb(var(--color-error-500) / <alpha-value>)",
          600: "rgb(var(--color-error-600) / <alpha-value>)",
          700: "rgb(var(--color-error-700) / <alpha-value>)",
          800: "rgb(var(--color-error-800) / <alpha-value>)",
          900: "rgb(var(--color-error-900) / <alpha-value>)",
          950: "rgb(var(--color-error-950) / <alpha-value>)",
        },
        // Success states
        success: {
          0: "rgb(var(--color-success-0) / <alpha-value>)",
          50: "rgb(var(--color-success-50) / <alpha-value>)",
          100: "rgb(var(--color-success-100) / <alpha-value>)",
          200: "rgb(var(--color-success-200) / <alpha-value>)",
          300: "rgb(var(--color-success-300) / <alpha-value>)",
          400: "rgb(var(--color-success-400) / <alpha-value>)",
          500: "rgb(var(--color-success-500) / <alpha-value>)",
          600: "rgb(var(--color-success-600) / <alpha-value>)",
          700: "rgb(var(--color-success-700) / <alpha-value>)",
          800: "rgb(var(--color-success-800) / <alpha-value>)",
          900: "rgb(var(--color-success-900) / <alpha-value>)",
          950: "rgb(var(--color-success-950) / <alpha-value>)",
        },
        // Warning states
        warning: {
          0: "rgb(var(--color-warning-0) / <alpha-value>)",
          50: "rgb(var(--color-warning-50) / <alpha-value>)",
          100: "rgb(var(--color-warning-100) / <alpha-value>)",
          200: "rgb(var(--color-warning-200) / <alpha-value>)",
          300: "rgb(var(--color-warning-300) / <alpha-value>)",
          400: "rgb(var(--color-warning-400) / <alpha-value>)",
          500: "rgb(var(--color-warning-500) / <alpha-value>)",
          600: "rgb(var(--color-warning-600) / <alpha-value>)",
          700: "rgb(var(--color-warning-700) / <alpha-value>)",
          800: "rgb(var(--color-warning-800) / <alpha-value>)",
          900: "rgb(var(--color-warning-900) / <alpha-value>)",
          950: "rgb(var(--color-warning-950) / <alpha-value>)",
        },
        // Info states
        info: {
          0: "rgb(var(--color-info-0) / <alpha-value>)",
          50: "rgb(var(--color-info-50) / <alpha-value>)",
          100: "rgb(var(--color-info-100) / <alpha-value>)",
          200: "rgb(var(--color-info-200) / <alpha-value>)",
          300: "rgb(var(--color-info-300) / <alpha-value>)",
          400: "rgb(var(--color-info-400) / <alpha-value>)",
          500: "rgb(var(--color-info-500) / <alpha-value>)",
          600: "rgb(var(--color-info-600) / <alpha-value>)",
          700: "rgb(var(--color-info-700) / <alpha-value>)",
          800: "rgb(var(--color-info-800) / <alpha-value>)",
          900: "rgb(var(--color-info-900) / <alpha-value>)",
          950: "rgb(var(--color-info-950) / <alpha-value>)",
        },
        // Typography colors
        typography: {
          0: "rgb(var(--color-typography-0) / <alpha-value>)",
          50: "rgb(var(--color-typography-50) / <alpha-value>)",
          100: "rgb(var(--color-typography-100) / <alpha-value>)",
          200: "rgb(var(--color-typography-200) / <alpha-value>)",
          300: "rgb(var(--color-typography-300) / <alpha-value>)",
          400: "rgb(var(--color-typography-400) / <alpha-value>)",
          500: "rgb(var(--color-typography-500) / <alpha-value>)",
          600: "rgb(var(--color-typography-600) / <alpha-value>)",
          700: "rgb(var(--color-typography-700) / <alpha-value>)",
          800: "rgb(var(--color-typography-800) / <alpha-value>)",
          900: "rgb(var(--color-typography-900) / <alpha-value>)",
          950: "rgb(var(--color-typography-950) / <alpha-value>)",
        },
        // Background colors
        background: {
          0: "rgb(var(--color-background-0) / <alpha-value>)",
          50: "rgb(var(--color-background-50) / <alpha-value>)",
          100: "rgb(var(--color-background-100) / <alpha-value>)",
          200: "rgb(var(--color-background-200) / <alpha-value>)",
          300: "rgb(var(--color-background-300) / <alpha-value>)",
          400: "rgb(var(--color-background-400) / <alpha-value>)",
          500: "rgb(var(--color-background-500) / <alpha-value>)",
          600: "rgb(var(--color-background-600) / <alpha-value>)",
          700: "rgb(var(--color-background-700) / <alpha-value>)",
          800: "rgb(var(--color-background-800) / <alpha-value>)",
          900: "rgb(var(--color-background-900) / <alpha-value>)",
          950: "rgb(var(--color-background-950) / <alpha-value>)",
          error: "rgb(var(--color-background-error) / <alpha-value>)",
          warning: "rgb(var(--color-background-warning) / <alpha-value>)",
          success: "rgb(var(--color-background-success) / <alpha-value>)",
          info: "rgb(var(--color-background-info) / <alpha-value>)",
          muted: "rgb(var(--color-background-muted) / <alpha-value>)",
        },
        // Outline/border colors
        outline: {
          0: "rgb(var(--color-outline-0) / <alpha-value>)",
          50: "rgb(var(--color-outline-50) / <alpha-value>)",
          100: "rgb(var(--color-outline-100) / <alpha-value>)",
          200: "rgb(var(--color-outline-200) / <alpha-value>)",
          300: "rgb(var(--color-outline-300) / <alpha-value>)",
          400: "rgb(var(--color-outline-400) / <alpha-value>)",
          500: "rgb(var(--color-outline-500) / <alpha-value>)",
          600: "rgb(var(--color-outline-600) / <alpha-value>)",
          700: "rgb(var(--color-outline-700) / <alpha-value>)",
          800: "rgb(var(--color-outline-800) / <alpha-value>)",
          900: "rgb(var(--color-outline-900) / <alpha-value>)",
          950: "rgb(var(--color-outline-950) / <alpha-value>)",
        },
        // Focus ring indicator
        indicator: {
          primary: "rgb(var(--color-indicator-primary) / <alpha-value>)",
          info: "rgb(var(--color-indicator-info) / <alpha-value>)",
          error: "rgb(var(--color-indicator-error) / <alpha-value>)",
        },
        // Legacy aliases for backward compatibility
        danger: "rgb(var(--color-error-500) / <alpha-value>)",
        cream: "rgb(var(--color-background-50) / <alpha-value>)",
      },
      fontFamily: {
        sans: ["Plus-Jakarta", "system-ui"],
        heading: ["Fjalla-One", "system-ui"],
      },
      fontSize: {
        "2xs": ["10px", { lineHeight: "12px" }],
        xs: ["12px", { lineHeight: "16px" }],
        sm: ["14px", { lineHeight: "20px" }],
        md: ["16px", { lineHeight: "24px" }],
        lg: ["18px", { lineHeight: "28px" }],
        xl: ["20px", { lineHeight: "28px" }],
        "2xl": ["24px", { lineHeight: "32px" }],
        "3xl": ["30px", { lineHeight: "36px" }],
        "4xl": ["36px", { lineHeight: "40px" }],
        "5xl": ["48px", { lineHeight: "1" }],
      },
      borderRadius: {
        none: "0",
        xs: "2px",
        sm: "4px",
        md: "6px",
        lg: "8px",
        xl: "12px",
        "2xl": "16px",
        "3xl": "24px",
        full: "9999px",
      },
      spacing: {
        0.5: "2px",
        1: "4px",
        1.5: "6px",
        2: "8px",
        2.5: "10px",
        3: "12px",
        3.5: "14px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "36px",
        10: "40px",
        12: "48px",
        16: "64px",
        20: "80px",
        24: "96px",
        32: "128px",
      },
    },
  },
  plugins: [],
};
